[package]
name = "aptos-type-accessor"
description = "Aptos Type Accessor"
version = "0.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos-api-types = { workspace = true }
aptos-rest-client = { workspace = true }
aptos-types = { workspace = true }
async-trait = { workspace = true }
enum_dispatch = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
aptos-framework = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
