[package]
name = 'piggy_bank'
version = '1.0.0'

[addresses]
token_objects = "_"

[dependencies]
AptosFramework = { local = "../../../../framework/aptos-framework" }
AptosTokenObjects = { local = "../../../../framework/aptos-token-objects" }
