[package]
name = "DataStructure"
version = "0.0.1"

[dependencies]
AptosStdlib = { local = "../../framework/aptos-stdlib" }

[addresses]
dport_collections = "0xb078d693856a65401d492f99ca0d6a29a0c5c0e371bc2521570a86e40d95f823"
